Feature: Preencher formulario, passando por abas 'Enter Vehicle Data', 'Enter Insurant Data', 'Enter Product Data', 'Select Price Option' e 'Send Quote'.

  Scenario: Preencher formulario corretamente
    Given que estou na pagina inicial
    When selecionar aba 'Enter Vehicle Data'
    And selecionar campo Make com valor 'Opel'
    And selecionar campo Model com valor 'Moped'
    And inserir campo CylinderCapacity com valor '1999'
    And inserir campo Engine Performance com valor '1999'
    And inserir campo Date of Manufacture com valor '10/26/2021'
    And selecionar campo Number of Seats com valor '5'
    And selecionar campo Right Hand Drive com valor 'No'
    And selecionar campo Number of Seats Motorcycle com valor '3'
    And selecionar campo Fuel Type com valor 'Gas'
    And selecionar campo Payload com valor '15'
    And inserir campo Total Weight com valor '101'
    And inserir campo List Price com valor '500'
    And inserir campo License Plate Number com valor 'A12457'
    And inserir campo Annual Mileage com valor '100000'
    And clico no botao Next em aba 'Enter Vehicle Data'
    And selecionar aba 'Enter Insurant Data'
    And inserir campo <First Name> com valor 'Gabriela'
    And inserir campo <Last Name> com valor 'Gomes'
    And inserir campo <Date of Birth> com valor '10/26/2003'
    And selecionar campo <Gender> com valor 'Female'
    And inserir campo <Street Address> com valor 'Rua dos Maues'
    And selecionar campo <Country> com valor 'Italy'
    And inserir campo <Zip Code> com valor '31570030'
    And inserir campo <City> com valor 'Belo Horizonte'
    And selecionar campo <Occupation> com valor 'Employee'
    And selecionar campo <Hobbies> com valor 'Speeding,Bungee jumping,Skydiving'
    And inserir campo <Website> com valor 'www.google.com.br'
    And inserir campo <Picture>
    And clico no botao Next em aba 'Enter Insurant Data'
    And selecionar aba 'Enter Product Data'
    And inserir campo <Start Date> com valor '28/10/2021'
    And selecionar campo <Insurance Sum> com valor ''
    And selecionar campo <Merit Rating> com valor ''
    And selecionar campo <Damage Insurance> com valor ''
    And selecionar campo <Optional Products> com valor ''
    And selecionar campo <Courtesy Car> com valor ''
    And clico no botao Next em aba 'Enter Product Data'
    And selecionar aba 'Select Price Option'
    And selecionar aba 'Select Price Option'
    And selecionar <price> com valor ''
    And clico no botao View Quote para analisar
    And selecionar aba 'Send Quote'
    Then deverá ser exibida mensagem 'Sending e-mail success!' em tela